problem:
  class: com.knezevic.edaf.testing.problems.MaxOnes
  genotype:
    type: binary
    length: 20
    crossing:
      name: one-point
      probability: 0.8
    mutation:
      name: simple
      probability: 0.2

algorithm:
  name: ega
  population:
    size: 500
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 10000
  log-frequency: 10
  log-directory: "logs/ega-max-ones"
