problem:
  class: com.knezevic.edaf.testing.problems.Rosenbrock
  optimization: min
  genotype:
    type: fp
    length: 10
    l-bound: -5.0
    u-bound: 5.0

algorithm:
  name: nes
  population:
    size: 100
  selection:
    name: tournament
    size: 3
  termination:
    max-generations: 1000
